### ISSUE TITLE
Footer is inappropriate on multiple domains.

### ISSUE THREAD

**Issue by zuzak** [OAOSIDL/oaosidl-site#14]
At the moment, the site footer mentions:

> abercompsci.co.uk is cheerfully maintained[...]

This also happens when viewing the site at other domains, such as [oaosidl.org](http://oaosidl.org). This is suboptimal; it should dynamically change depending on the domain name, or rephrased to avoid the issue.

**Comment by SamStudio8** [comment]
@zuzak The footer refers to the name of the repository itself, I am considering a rename of the repo as oaosidl.org is more apt than abercompsci.co.uk.

**Comment by debuos512** [comment]
Agreed with above
